### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yorickdowne** [CryptoManufaktur-io/accounting#2]
- [ ] README
- [x] Move config into a toml
- [x] Auto-increment sheet name by year
- [ ] Add Terra payment tracking
- [x] DRY out config.toml some by adding chains
- [ ] Gracefully recover from missing worksheet instead of failing
- [ ] Gracefully recover from missing or malformed config / credential files
- [ ] Better funding discovery, or remove altogether
- [ ] Gracefully recover from RPC errors
- [ ] RPC failover? Could be haproxy instead
